### ISSUE TITLE
It works, but the client disconnects instantly when connecting.

### ISSUE THREAD

**Issue by random-player** [sethdm02/Ogar-Unlimited-With-Client#1]
It works, but the client disconnects instantly when connecting. I need help for this! IDK what's going on. How can I fix it?

**Comment by random-player** [comment]
It gives me this in console.
![bandicam 2018-05-13 03-18-47-879](https://user-images.githubusercontent.com/26576570/39962596-5dfda526-565c-11e8-8e21-0bda000f84c5.png) I need help!

**Comment by jerk** [comment]
is that the port you chose?

**Comment by random-player** [comment]
Yes. 443 or 7251.
What happens is that the client manages to connect to my server, but disconnects instantly for no reason. Even with the port being 443, It has the same result.

**Comment by random-player** [comment]
I tested the same steps in the 2nd issue, same result. I removed line 480 - 484 on main_out.js. It seems like that every connection it finds, it wants to disconnect. I guess that main_out.js is faulty.

**Comment by jerk** [comment]
ill look

**Comment by random-player** [comment]
I am using Node.js v5.12.0.

**Comment by random-player** [comment]
I changed to Node.js v8.11.2.

**Comment by random-player** [comment]
For me, I found it! It's actually OgarUL's fault. If it finds a connection, it instantly regrets it. So it disconnects. 16.7.8 works fine, but not 17.6.0.

**Comment by random-player** [comment]
No comments in almost 3 months. Closing issue.

**Comment by CruelAlpha** [comment]
How was this fixed?
Cheers
