### ISSUE TITLE
how to deploy

### ISSUE THREAD

**Issue by Faris90** [sethdm02/Ogar-Unlimited-With-Client#2]
How could I deploy Ogar unlimited to Heroku??

**Comment by jerk** [comment]
Make sure git is installed...
1. git clone https://github.com/sethdm02/Ogar-Unlimited-With-Client.git
Install nodejs 
For Debian/Ubuntu sudo apt-get install nodejs
For CentOs and other OS'es with "yum" command
yum install nodejs
2. cd Ogar-Unlimited-With-Client
3. npm install
4. cd src/plugins/client
4. npm install
5. then go back to "src"
6. node index.js
7. then portforward if not already "should of by itself"
8. then go to your system ip or what ever it is

**Comment by Faris90** [comment]
I mean Heroku

**Comment by jerk** [comment]
have no clue buddy

**Comment by Agarian** [comment]
@Faris90 Was that just you that decided to get into my Cloud9 workspace? *For the record, I denied you access to it now*, but still man, not cool

**Comment by Faris90** [comment]
no
